### ISSUE TITLE
bower is not found when doing bower update but it did install the packages in the npm install step

### ISSUE THREAD

**Issue by LJNielsenDk** [angular/angular-seed#383] opened 2016-11-19 09:54 UTC
Am I supposed to add it to the path myself or should it just work? If the former, the guide should probably mention this.

I'm on Windows 10 using node v7.0.0 and running the commands in it's Node.js command prompt.

I have tried running bower update in the same Node.js command prompt as npm install and a new one opened after that step.

Am I doing/expecting something silly, is something broken, or does the guide need updating?

**Comment by deminyx** [comment] 2016-11-19 15:29
Got the same problem a few minutes ago...

**Comment by gkalpak** [comment] 2016-11-21 08:24
In order to avoid poluting your global packages or suffer from version-mismatch issues, `angular-seed` does not rely on a global `bower` installation. If you want to be able to run `bower <command>` directly from the terminal, you can install `bower` globally with `npm install --global bower` (but it is not necessary for `angular-seed`).

Instead, `angular-seed` installs and runs `bower` locally (as a local npm dependency). The project is set up to automatically run `bower install` right after `npm install`, so you don't have to manually run it. The reason this works from within the post-install npm script, is that npm scripts can also find local executables; i.e. those in `node_modules/.bin/`.

If you want to manually run `bower` without a global installation, you can run `node_modules/.bin/bower.cmd <command>` from inside the projects root directory.

<sub>Closing, since everything works as intended.</sub>

**Comment by gkalpak** [comment] 2016-11-21 11:28
I just realized we suggest running `bower update` in [README][1] as a way to update bower dependencies. That will clearly not work unless `bower` is installed globally. I will submit a PR with a fix shortly.

[1]: https://github.com/angular/angular-seed/blob/437e0bb3eb1f8fbb7a034ee38e51f474748f6ac7/README.md#updating-angular

**Closed** 2016-11-21 18:00 UTC
